version: '3.9'

services:
  frontend-scoring:
    build: ./frontend_scoring
    restart: always
  frontend-profile:
    build: ./frontend_profile
    restart: always
  backend:
    build: ./backend
    restart: always
  reverse-proxy:
    build: ./reverse-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend-scoring
      - frontend-profile
      - backend
    volumes:
      - /certbot/www:/var/www/certbot/:ro
      - /certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - /certbot/www/:/var/www/certbot/:rw
      - /certbot/conf/:/etc/letsencrypt/:rw