version: "3.9"

services:
  frontend-scoring:
    build:
      context: ./frontend_scoring
      dockerfile: Dockerfile-dev

    restart: always
    volumes:
      - ./frontend_scoring:/app
      - /app/node_modules
  frontend-profile:
    build:
      context: ./frontend_profile
      dockerfile: Dockerfile-dev
    restart: always
    volumes:
      - ./frontend_profile:/app
      - /app/node_modules
  # mysql:
  #   image: mysql:8
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: db
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #   restart: always
  # volumes:
  #   - ./data/db_data:/var/lib/mysql
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
  backend:
    build: ./backend
    restart: always
    # depends_on:
    #   - mysql
  reverse-proxy:
    build: ./reverse-proxy
    restart: always
    ports:
      - 80:80
    depends_on:
      - frontend-profile
      - frontend-scoring
      - backend
