version: '3.9'

services:
  frontend-scoring:
    build: ./frontend_scoring
    restart: always
    volumes: 
      - ./frontend_scoring:/app
      - /app/node_modules
  frontend-profile:
    build: ./frontend_profile
    restart: always
    volumes: 
      - ./frontend_profile:/app
      - /app/node_modules
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
  backend:
    build: ./backend
    restart: always
  reverse-proxy:
    build: ./reverse-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend-scoring
      - frontend-profile
      - backend
#    volumes:
#      - /certbot/www:/var/www/certbot/:ro
#      - /certbot/conf/:/etc/nginx/ssl/:ro
#  certbot:
#    image: certbot/certbot:latest
#    volumes:
#      - /certbot/www/:/var/www/certbot/:rw
#      - /certbot/conf/:/etc/letsencrypt/:rw
